# Generated by Django 5.2.8 on 2025-11-10 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=1000)),
                ('date', models.DateField(default=datetime.datetime(2025, 11, 10, 20, 26, 1, 706721))),
            ],
        ),
    ]
