# Generated by Django 5.2.8 on 2025-11-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_articles_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
